<Card>
    radius: 12
    orientation: "vertical"
    padding: "12dp", 0, "12dp", "24dp"
    style: "elevated"
    on_release: app.on_card_release(root.text)

    Image:
        source: root.source

    MDLabel:
        text: root.text
        halign: "center"
        adaptive_height: True
        font_name: "assets/fonts/Cairo/Cairo-Bold.ttf"
        line_height: .6
        font_size: "16sp"