<RootScreen>

    MDBottomNavigation:

        MDBottomNavigationItem:
            name: "today screen"
            icon: "calendar"
            text: "Today"

            TodayScreen

        MDBottomNavigationItem:
            name: "all exercise screen"
            icon: "dumbbell"
            text: "All Exercise"


            AllExercise:


        MDBottomNavigationItem:
            name: "settings screen"
            icon: "cog"
            text: "Settings"